#!/usr/bin/env python

import sys

from rqt_gui.main import Main

def add_arguments(parser):
    group = parser.add_argument_group('Options for tocabi_gui plugin')
    group.add_argument('topic', nargs='?', help='The topic name to subscribe to')

main = Main()
sys.exit(main.main(
    sys.argv, 
    standalone='tocabi_gui/TocabiGui',
    plugin_argument_provider=add_arguments))